package javathsiaproject;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static javathsiaproject.sonToModuleFFT.convertSonModule;

public class main {
    public static void main (String[] args) {
        //exemple de fonctionnement de la fonction convertSonModule
        convertSonModule("/home/maxou/Documents/projet/projetGit/JAVA-THS-IA-PROJECT/JavaThsIaProject/app/src/main/resources/audio/Carre.wav");
    }
}

