package javathsiaproject;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import FFT.Complexe;
import FFT.ComplexeCartesien;
import Son.Son;
import javathsiaproject.converteurComplex;

import FFT.FFTCplx;

import static FFT.FFTCplx.appliqueSur;


public class main {
 static Son son = new Son("/home/maxou/Documents/projet/projetGit/JAVA-THS-IA-PROJECT/JavaThsIaProject/app/src/main/resources/audio/Sinusoide.wav");

    public static void main (String[] args) {
        System.out.println("resultat : "+son.donnees());
        for (int i = 0; i < son.bloc_deTaille(1,512).length; ++i){
            System.out.println("bloc : "+son.bloc_deTaille(1,512)[i]);
        }
        ComplexeCartesien[] tablo = converteurComplex.convertirEnComplexe(son.bloc_deTaille(1,512));
        Complexe[] resultat = appliqueSur(tablo);
        for (int i = 0; i < resultat.length; ++i){
            System.out.println("resultat : "+resultat[i].reel()+"+"+resultat[i].imag());
        }
    }
}

