/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javathsiaproject;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        main classUnderTest = new main();

    }
}
